#!/usr/bin/env python3
"""Regenerates src/ui/fonts_embedded.cpp from assets/fonts/*.ttf.

Fonts are compiled into the binary so the app never depends on a working
directory or install layout (identical behaviour on Windows, macOS, Linux).
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
fonts = {
    "font_ui_regular": "LatoLatin-Regular.ttf",
    "font_ui_bold": "LatoLatin-Bold.ttf",
    "font_mono": "Cousine-Regular.ttf",
}
out = ["// Generated by tools/embed_fonts.py - do not edit by hand.",
       "// Lato (SIL OFL 1.1), Cousine (Apache 2.0).",
       '#include "fonts_embedded.hpp"', "", "namespace ui::fonts {"]
for sym, fname in fonts.items():
    data = (root / "assets" / "fonts" / fname).read_bytes()
    out.append(f"static const unsigned char {sym}_data[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        out.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    out.append("};")
    out.append(f"const Blob {sym} = {{ {sym}_data, sizeof({sym}_data) }};")
out.append("} // namespace ui::fonts")
(root / "src" / "ui" / "fonts_embedded.cpp").write_text("\n".join(out) + "\n")
print("ok")
