#!/usr/bin/env python3
"""Builds the GPU renderer's compute shaders into src/gpu/shaders_gen.cpp.

Every shader in src/gpu/shaders/*.comp (GLSL 4.50) is compiled once per
SDL_GPU shader format, so building Orbit64 needs no shader tools:

  SPIR-V  glslangValidator                        (Vulkan: Linux, Windows)
  MSL     glslangValidator -DTARGET_MSL, then     (Metal: macOS)
          spirv-cross --msl --msl-decoration-binding
  HLSL    spirv-cross --hlsl --shader-model 51    (Direct3D 12: compiled to
                                                  DXBC at run time)

Run it after editing a shader:  python3 tools/gen_shaders.py
Needs glslangValidator and spirv-cross on PATH (brew install glslang
spirv-cross, apt install glslang-tools spirv-cross, or the Vulkan SDK).
"""

import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADER_DIR = os.path.join(ROOT, "src", "gpu", "shaders")
OUT = os.path.join(ROOT, "src", "gpu", "shaders_gen.cpp")


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("failed: %s\n%s%s" % (" ".join(cmd), r.stdout, r.stderr))
    return r.stdout


def compile_shader(path, tmp):
    name = os.path.splitext(os.path.basename(path))[0]
    spv = os.path.join(tmp, name + ".spv")
    spv_msl = os.path.join(tmp, name + "_msl.spv")
    run(["glslangValidator", "-V", "--target-env", "vulkan1.0", "-I" + SHADER_DIR, "-o", spv, path])
    run(["glslangValidator", "-V", "--target-env", "vulkan1.0", "-DTARGET_MSL", "-I" + SHADER_DIR, "-o", spv_msl, path])
    msl = run(["spirv-cross", spv_msl, "--msl", "--msl-version", "20100", "--msl-decoration-binding"])
    hlsl = run(["spirv-cross", spv, "--hlsl", "--shader-model", "51"])
    with open(spv, "rb") as f:
        spirv = f.read()
    return name, spirv, msl, hlsl


def c_words(data):
    # SPIR-V is a stream of 32-bit words.
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    lines = []
    for i in range(0, len(words), 10):
        lines.append("    " + ", ".join("0x%08x" % w for w in words[i:i + 10]) + ",")
    return "\n".join(lines)


def c_text(text):
    # Raw string literals of at most ~12 KB each (MSVC caps a literal at 16 KB,
    # a concatenation at 64 KB), split at line ends, joined at run time.
    parts, cur = [], ""
    for line in text.splitlines(keepends=True):
        if len(cur) + len(line) > 12000 and cur:
            parts.append(cur)
            cur = ""
        cur += line
    if cur:
        parts.append(cur)
    for p in parts:
        assert ")orbit\"" not in p
    return "\n".join('    R"orbit(%s)orbit",' % p for p in parts) + "\n    nullptr,"


def main():
    shaders = sorted(f for f in os.listdir(SHADER_DIR) if f.endswith(".comp"))
    with tempfile.TemporaryDirectory() as tmp:
        built = [compile_shader(os.path.join(SHADER_DIR, s), tmp) for s in shaders]
    parts = [
        "// Generated by tools/gen_shaders.py from src/gpu/shaders/*.comp. Do not edit.",
        '#include "shaders_gen.hpp"',
        "",
        "namespace gpu::shaders {",
        "",
    ]
    for name, spirv, msl, hlsl in built:
        parts += [
            "static const unsigned int %s_spirv[] = {" % name,
            c_words(spirv),
            "};",
            "static const char* const %s_msl[] = {" % name,
            c_text(msl),
            "};",
            "static const char* const %s_hlsl[] = {" % name,
            c_text(hlsl),
            "};",
            "const Blob %s = {reinterpret_cast<const unsigned char*>(%s_spirv), sizeof(%s_spirv), %s_msl, %s_hlsl};"
            % (name, name, name, name, name),
            "",
        ]
    parts += [
        "std::string text(const char* const* parts) {",
        "    std::string s;",
        "    for (; *parts; ++parts) s += *parts;",
        "    return s;",
        "}",
        "",
    ]
    parts.append("} // namespace gpu::shaders")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote %s (%s)" % (os.path.relpath(OUT, ROOT), ", ".join(b[0] for b in built)))


if __name__ == "__main__":
    main()
