#!/usr/bin/env python3
"""Builds the Vulkan-only compute shaders in src/gpu/shaders/ext/*.comp into
src/gpu/shaders_ext_gen.cpp: per-pixel ray tracing (rt_*) and the
post-processing chain (pfx_*).

Unlike tools/gen_shaders.py these are SPIR-V only (no Metal or Direct3D
versions): the features they drive are off on those drivers. Needs glslc
(the Vulkan SDK's, or the Android NDK's shader-tools) on PATH or in $GLSLC.

Run it after editing one of them:  python3 tools/gen_ext_shaders.py
"""

import glob
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADER_DIR = os.path.join(ROOT, "src", "gpu", "shaders", "ext")
OUT = os.path.join(ROOT, "src", "gpu", "shaders_ext_gen.cpp")


def find_glslc():
    if os.environ.get("GLSLC"):
        return os.environ["GLSLC"]
    found = shutil.which("glslc")
    if found:
        return found
    sdk = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Android", "Sdk", "ndk")
    hits = sorted(glob.glob(os.path.join(sdk, "*", "shader-tools", "*", "glslc*")))
    if hits:
        return hits[-1]
    sys.exit("glslc not found: put it on PATH or set GLSLC")


def main():
    glslc = find_glslc()
    shaders = sorted(f for f in os.listdir(SHADER_DIR) if f.endswith(".comp"))
    parts = [
        "// Generated by tools/gen_ext_shaders.py from src/gpu/shaders/ext/*.comp. Do not edit.",
        '#include "shaders_ext_gen.hpp"',
        "",
        "namespace gpu::shaders {",
        "",
    ]
    with tempfile.TemporaryDirectory() as tmp:
        for s in shaders:
            name = os.path.splitext(s)[0]
            spv = os.path.join(tmp, name + ".spv")
            r = subprocess.run([glslc, "-fshader-stage=compute", "--target-env=vulkan1.0", "-O",
                                os.path.join(SHADER_DIR, s), "-o", spv], capture_output=True, text=True)
            if r.returncode != 0:
                sys.exit("failed: %s\n%s%s" % (s, r.stdout, r.stderr))
            data = open(spv, "rb").read()
            words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
            parts.append("static const unsigned int %s_spirv[] = {" % name)
            for i in range(0, len(words), 10):
                parts.append("    " + ", ".join("0x%08x" % w for w in words[i:i + 10]) + ",")
            parts.append("};")
            parts.append("const SpirvBlob %s = {reinterpret_cast<const unsigned char*>(%s_spirv), sizeof(%s_spirv)};"
                         % (name, name, name))
            parts.append("")
    parts.append("} // namespace gpu::shaders")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote %s (%s)" % (os.path.relpath(OUT, ROOT), ", ".join(shaders)))


if __name__ == "__main__":
    main()
