#pragma once
// The GPU renderer's compute shaders in every format SDL_GPU takes
// (src/gpu/shaders_gen.cpp, generated by tools/gen_shaders.py).

#include <cstddef>
#include <string>

namespace gpu::shaders {

struct Blob {
    const unsigned char* spirv; // Vulkan; entry point "main"
    std::size_t spirv_size;
    const char* const* msl;     // Metal source (pieces, see text()); entry point "main0"
    const char* const* hlsl;    // Direct3D (shader model 5.1) source; entry point "main"
};

// A source kept in pieces (a null-terminated list), joined.
std::string text(const char* const* parts);

extern const Blob compose; // compose.comp
extern const Blob decode;  // decode.comp
extern const Blob exact_apply;  // exact_apply.comp
extern const Blob exact_init;   // exact_init.comp
extern const Blob exact_memory; // exact_memory.comp
extern const Blob exact_shade;  // exact_shade.comp
extern const Blob exact_shade_2cycle; // exact_shade_2cycle.comp
extern const Blob exact_shade_copy; // exact_shade_copy.comp
extern const Blob exact_shade_fill; // exact_shade_fill.comp
extern const Blob exact_shade_flat; // exact_shade_flat.comp
extern const Blob exact_shade_tex1; // exact_shade_tex1.comp
extern const Blob fill;    // fill.comp
extern const Blob raster;  // raster.comp

} // namespace gpu::shaders
