#pragma once
// The GPU renderer's compute shaders in every format SDL_GPU takes
// (src/gpu/shaders_gen.cpp, generated by tools/gen_shaders.py).

#include <cstddef>

namespace gpu::shaders {

struct Blob {
    const unsigned char* spirv; // Vulkan; entry point "main"
    std::size_t spirv_size;
    const char* msl;            // Metal source; entry point "main0"
    const char* hlsl;           // Direct3D (shader model 5.1) source; entry point "main"
};

extern const Blob compose; // compose.comp
extern const Blob decode;  // decode.comp
extern const Blob fill;    // fill.comp
extern const Blob raster;  // raster.comp

} // namespace gpu::shaders
