#pragma once
// Vulkan-only compute shaders (src/gpu/shaders_ext_gen.cpp, generated by
// tools/gen_ext_shaders.py from src/gpu/shaders/ext/*.comp).

#include <cstddef>

namespace gpu::shaders {

struct SpirvBlob {
    const unsigned char* spirv; // entry point "main"
    std::size_t size;
};

extern const SpirvBlob rt_apply; // per-pixel ray tracing: filter and apply
extern const SpirvBlob rt_trace; // per-pixel ray tracing: the rays

} // namespace gpu::shaders
